import { useState } from 'react';
import { projectRequest, projectsChanged, useProjects } from '../hooks/useProjects';
export default function Projects({teamId,projectId,onSelect}:{teamId:string;projectId:string;onSelect:(id:string)=>void}){
 const {items,error,loaded}=useProjects(teamId);const [show,setShow]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState(''),[editing,setEditing]=useState(''),[busy,setBusy]=useState(false),[failure,setFailure]=useState('');
 const selected=items.find(p=>p.id===projectId);
 async function action(action:string,body:unknown){setBusy(true);setFailure('');try{await projectRequest(teamId,action,body);projectsChanged();setShow(false);}catch(e){setFailure(e instanceof Error?e.message:'Unable to save project.');}finally{setBusy(false);}}
 return <section className="board-projects" aria-label="Projects"><div className="project-board-filters"><label>Project <select aria-label="Filter by project" value={projectId} disabled={busy||!loaded} onChange={e=>onSelect(e.target.value)}><option value="all">All projects</option><option value="">Unassigned</option>{items.map(p=><option key={p.id} value={p.id}>{p.name}{p.archived?' (archived)':''}</option>)}</select></label><button disabled={busy||!loaded} onClick={()=>{setEditing('');setName('');setDescription('');setShow(true);}}>New project</button>{selected?.canManage&&<><button disabled={busy} onClick={()=>{setEditing(selected.id);setName(selected.name);setDescription(selected.description);setShow(true);}}>Edit project</button><button disabled={busy} onClick={()=>void action('archive',{id:selected.id,archived:!selected.archived})}>{selected.archived?'Restore project':'Archive project'}</button></>}</div>
 {selected?.description&&<p>{selected.description}</p>}{(error||failure)&&<p role="alert">{error||failure}</p>}
 {show&&<form className="project-board-fields" onSubmit={e=>{e.preventDefault();void action(editing?'update':'create',{id:editing,name,description});}}><label>Project name<input required maxLength={120} value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>Project description<textarea maxLength={4000} value={description} disabled={busy} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy}>Save project</button><button type="button" disabled={busy} onClick={()=>setShow(false)}>Cancel</button></form>}
 </section>;
}
export function TaskProject({teamId,taskId,canEdit}:{teamId:string;taskId:string;canEdit:boolean}){
 const {items,assignments,canAssignAny,error,loaded}=useProjects(teamId);const [busy,setBusy]=useState(false),[failure,setFailure]=useState('');const id=assignments.find(a=>a.task===taskId)?.project_id||'';
 async function assign(projectId:string){setBusy(true);setFailure('');try{await projectRequest(teamId,'assign',{task:taskId,projectId});projectsChanged();}catch(e){setFailure(e instanceof Error?e.message:'Assignment failed.');}finally{setBusy(false);}}
 return <section className="project-board-fields"><label>Project<select aria-label="Task project" value={id} disabled={!loaded||busy||!(canEdit||canAssignAny)} onChange={e=>void assign(e.target.value)}><option value="">Unassigned</option>{items.filter(p=>!p.archived||p.id===id).map(p=><option key={p.id} value={p.id} disabled={!!p.archived}>{p.name}{p.archived?' (archived)':''}</option>)}</select></label>{(error||failure)&&<p role="alert">{error||failure}</p>}</section>;
}
